[build]
  base = "."                  # Start from the root of your repo
  publish = "frontend/build"  # Explicit path to your build folder
  command = "cd frontend && npm run build"  # Ensures build runs in the right directory